name: GriefProtect
version: '${project.version}'
main: lycoris.griefprotect.GriefProtect
api-version: '1.20'
folia-supported: true
dependencies:
  server:
    Essentials:
      required: true
      join-classpath: true
    CoreProtect:
      required: true
      join-classpath: true
commands:
  playingtime:
    aliases: playingtime
  exchange:
    aliases: exchange
  testspawn:
    aliases: testspawn
  testfind:
    aliases: testfind
permissions:
  ag.bypass:
    description: "Allows to bypass the protection"
    default: op